management:
  endpoint:
    health:
      probes:
        enabled: true
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param
    include-exception: false